/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    String inputFilePath = "./src/main/resources/sample.bmp";
    String outputFilePath = "./src/main/resources/";
    String purpleFileName = "NewCoffeePurple.bmp";
    Bitmap testFile = new Bitmap(inputFilePath,outputFilePath, purpleFileName);

    @Test
    public void testReadFile() {
        assertEquals( true, testFile.readFile(),"File not found");
    }

    @Test
    public void testSaveFile() {
        testFile.readFile();
        assertEquals( true, testFile.saveFile() ,"File not saved");
    }

    @Test
    public void testPurpleIze() {
        testFile.readFile();
        assertEquals( -4553837, testFile.purpleIze() ,"Return: RGB(48, 29, 87)");
    }

    @Test
    public void testImageFlipHorizontal() {
        testFile.readFile();
        int lastRGBVal = -16513535;
        assertEquals( lastRGBVal, testFile.imageFlipHorizontal(),"File not flipped horizontally");
    }

    @Test
    public void testImageFlipVertical() {
        testFile.readFile();
        int lastRGBVal = -8759696;
        assertEquals( lastRGBVal, testFile.imageFlipVertical(),"File not flipped vertically");
    }
}
